# Generated by Django 4.2.1 on 2023-05-29 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('foundation_date', models.DateField(default=datetime.datetime(2023, 5, 29, 14, 6, 53, 700153, tzinfo=datetime.timezone.utc))),
                ('branch', models.CharField(choices=[('IT', 'IT'), ('Health', 'HEALTH'), ('Financial market', 'FINANCE'), ('Education', 'EDUCATION'), ('Energy', 'ENERGY'), ('Food', 'FOOD'), ('Other', 'OTHER')], max_length=255)),
            ],
        ),
    ]
