# Generated by Django 4.2.1 on 2023-05-29 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_registration', '0004_rename_members_company_employees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='branch',
            new_name='domain',
        ),
    ]
